package org.example.entity.enums;

public enum Degree {
    KARDANI,
    KARSHENASIPEYVASTE,
    KARSHENASINAPEYVASTE,
    KARSHENASIARSHAD,
    DOKTORAYHERFEI,
    DOKTORAYPEYVASTE,
    DOKTORAYTAKHASOSINAPEYVASTE,
}
